In [3]:
import pandas as pd
df=pd.read_csv("data.csv")

In [4]:
df

,Pallet ID,Product type,Product amount (ni),Size type (si),Pallet type,Release day (ri)
0,1,P1,110,1,100×120,1
1,2,P1,90,1,100×120,1
2,3,P2,125,1,100×120,2
3,4,P3,95,2,80×120,2
4,5,P3,115,1,100×120,1
5,6,P1,75,2,80×120,3
6,7,P3,135,1,100×120,3
7,8,P2,100,1,100×120,1
8,9,P3,90,1,100×120,2
9,10,P2,90,1,100×120,3
10,11,P1,80,2,80×120,2
11,12,P2,150,2,80×120,1
12,13,P3,125,1,100×120,3
13,14,P1,115,1,100×120,2
14,15,P2,50,2,80×120,1
15,16,P3,105,1,100×120,1
16,17,P1,95,2,80×120,2
17,18,P2,85,2,80×120,2
18,19,P3,75,2,80×120,1
19,20,P1,40,2,80×120,2